package at.technikum.firstui.event;

public enum Event {
    SEARCH_TERM_SELECTED,
    SEARCH_TERM_SEARCHED,
    TOUR_SELECTED,
    TOUR_ADDED,
    TOUR_LOG_ADDED,
    SELECTED_TOUR_CHANGED,
    SELECTED_TOUR_INDEX,
    TOUR_DELETED,
    TOUR_START_ADDED,
    TOUR_END_ADDED


}
